const mongoose = require('mongoose');

// Every SMS a paired phone forwards, with what the server made of it. This is
// the audit trail for automatic payment verification.
const incomingSmsSchema = new mongoose.Schema(
  {
    device: { type: mongoose.Schema.Types.ObjectId, ref: 'SmsDevice', required: true, index: true },
    // Generated by the phone (UUID) — makes re-sending the same message harmless.
    clientId: { type: String, required: true, maxlength: 80 },

    sender: { type: String, trim: true, default: '', maxlength: 64 },
    body: { type: String, default: '', maxlength: 2000 },
    receivedAt: { type: Date, required: true }, // when the phone got it

    provider: { type: String, default: '' }, // e.g. 'bkash' when a parser recognised it
    parsed: {
      kind: { type: String, default: '' }, // 'credit'
      amount: { type: Number, default: null },
      fee: { type: Number, default: null },
      balance: { type: Number, default: null },
      counterparty: { type: String, default: '' }, // the sender's wallet number
      trxId: { type: String, default: '', index: true },
      paidAt: { type: Date, default: null }, // time printed in the SMS
    },

    // received      – stored, not processed yet
    // ignored       – not from a sender/format we understand
    // duplicate     – same TrxID already seen
    // unmatched     – valid receipt, no waiting payment yet (kept; matched when an order arrives)
    // verified      – matched a payment and auto-verified it
    // needs_review  – matched a payment but amount / sender differs; an admin must decide
    // error         – processing failed
    status: {
      type: String,
      enum: ['received', 'ignored', 'duplicate', 'unmatched', 'verified', 'needs_review', 'error'],
      default: 'received',
      index: true,
    },
    note: { type: String, default: '' },
    payment: { type: mongoose.Schema.Types.ObjectId, ref: 'Payment', default: null },
    order: { type: mongoose.Schema.Types.ObjectId, ref: 'Order', default: null },
  },
  { timestamps: true }
);

incomingSmsSchema.index({ device: 1, clientId: 1 }, { unique: true });
incomingSmsSchema.index({ createdAt: -1 });

const ttlDays = Math.max(1, Number(process.env.SMS_LISTENER_LOG_RETENTION_DAYS || 90));
incomingSmsSchema.index({ createdAt: 1 }, { expireAfterSeconds: ttlDays * 24 * 60 * 60 });

module.exports = mongoose.model('IncomingSms', incomingSmsSchema);
